[book]
authors = ["meator"]
language = "en"
multilingual = false
title = "xbps-src tutorials"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
curly-quotes = true
git-repository-url = "https://github.com/meator/xbps-src-tutorials"
site-url = "/xbps-src-tutorials/"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.admonish]
command = "mdbook-admonish"

#[output.linkcheck]
